### ISSUE TITLE
document-convert 工具包进行文档解析时，英文单词间的空格丢失

### ISSUE THREAD

**Issue by uloveqian2021** [multimodal-art-projection/MAP-NEO#20]
如题；
example:
LCD/OLED display products, as well as the physics and chemistry performance requirements of LTPS process technology on glass
substrates.The most critical technical indicators are heat resistance, thermal expansion coefficient, UV transmittance, and elastic
nodulus. What's more we compared and analyzed the advantages and disadvantages of LTPS glass substrates produced by overflow
process and float process.Then we summarized the state of the glass substrate products developed by the United States andJapan to
meet the LTPS process. The research and development status of glass substrate in LTPS process in China is described. It is urgent to
increase investmentinresearchanddevelopment and industrialexploration.
Keywords: low temperature polysilicon (LTPS); liquid crystal display/organic light emitting display (LCD/OLED); glass substrate;
processtechnology:thermalproperties

**Comment by hahhforest** [comment]
老哥直接跑起来的multi_thread_process_to_doc.py吗，我的models/文件夹是空的，在手动下载paddle的模型，请问下你有没有遇到这个问题

**Comment by TaoTaoNie** [comment]
你直接可以跑起来吗？我这边一直报错：
WARNING:root:Due to the package size limitation, we have not provide fastdeploy-gpu-python on pypi yet, please execute the following commands to reinstall fastdeploy-gpu-python.
WARNING:root:   =================== Reinstall fastdeploy-gpu-python commands ==================
WARNING:root:   python -m pip uninstall fastdeploy-gpu-python
WARNING:root:   python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
Traceback (most recent call last):
  File "multi_thread_process_to_doc.py", line 5, in <module>
    import fastdeploy as fd
  File "/opt/conda/lib/python3.8/site-packages/fastdeploy/__init__.py", line 22, in <module>
    raise Exception("Failed to import fastdeploy module.")
Exception: Failed to import fastdeploy module.
但是fastdeploy-gpu-python这个我是安装好了的
