### ISSUE TITLE
error in batch_convert_ckpt

### ISSUE THREAD

**Issue by hanjr92** [multimodal-art-projection/MAP-NEO#32]
when i use `bash neo/scripts/batch_convert_ckpt.sh`:
```
Loaded loader_megatron_core as the loader.
Loaded saver_llama2_hf_bf as the saver.
Starting saver...
Starting loader...
Zarr-based strategies will not be registered because of missing packages
Checkpoint not found to provide arguments, using provided arguments.
Traceback (most recent call last):
  File "/workspace/megatron/tools/checkpoint/util.py", line 154, in <module>
    main()
  File "/workspace/megatron/tools/checkpoint/util.py", line 147, in main
Loader exited, exiting saver
    loader.load_checkpoint(queue, args)
  File "/workspace/megatron/tools/checkpoint/loader_megatron_core.py", line 390, in load_checkpoint
    _load_checkpoint(queue, args)
  File "/workspace/megatron/tools/checkpoint/loader_megatron_core.py", line 82, in _load_checkpoint
    margs, checkpoint_args = load_args_from_checkpoint(margs)
TypeError: cannot unpack non-iterable Namespace object
  0%|                                                                                            
```

**Comment by hanjr92** [comment]
i wish you can provide 2b hf-verison checkpoints.

**Comment by Kevinstone-199898** [comment]
Excuse me, I wonder where do you get the checkpoint? from huggingface?

**Comment by hanjr92** [comment]
> Excuse me, I wonder where do you get the checkpoint? from huggingface?

yes, i got 2b checkponits from huggingface. The checkpoints look like megatron version.  So, i encountered this error when i used tools to convert it.

**Comment by Kevinstone-199898** [comment]
You just direcctly run bash neo/scripts/batch_convert_ckpt.sh without any modification and then encountered this error?It seems that the loader runs correctly and the saver part is wrong

**Comment by hanjr92** [comment]
> You just direcctly run bash neo/scripts/batch_convert_ckpt.sh without any modification and then encountered this error?It seems that the loader runs correctly and the saver part is wrong

yes，i didn't modifiy any files. Maybe `neo/scripts/batch_convert_ckpt.sh` can only works on the 7b model？

**Comment by Kevinstone-199898** [comment]
No, I tried to convert 7B checkpoints, and the error occurred in the loader part

**Comment by hanjr92** [comment]
> No, I tried to convert 7B checkpoints, and the error occurred in the loader part

ok， it looks like there are some bugs in it.
