### ISSUE TITLE
Can docment convert a standalone project?

### ISSUE THREAD

**Issue by lucasjinreal** [multimodal-art-projection/MAP-NEO#4]
It;s should be very useful it the entrance can be more easy to found

**Comment by skyroot** [comment]
can u run "python multi_thread_process_to_doc.py ./pdf --process-num 8" success??

**Comment by lucasjinreal** [comment]
can not run it on mac M1 CPU

**Comment by lucasjinreal** [comment]
python multi_thread_process_to_doc.py ./pdf
usage: multi_thread_process_to_doc.py [-h] --recipe RECIPE [--loop] [--rest] [--build] [--config CONFIG]
multi_thread_process_to_doc.py: error: the following arguments are required: --recipe

**Comment by lucasjinreal** [comment]
Why using fastdeploy, it as big as  torch but acutally didn't get much speed boost.

**Comment by InsaneGe** [comment]
I have run through it by following commands on Windows Anaconda platform.
`conda create -n neo python=3.10
pip install -r requirements.txt
python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

Unfortunately I have to tell you is that the effect of pdf-parser is general, worse than calling the PPStructure when testing the Chinese paper pdf.

**Comment by lucasjinreal** [comment]
fastdeploy is the worse lib i have ever seen, it force to cuda11.8 even doesn't have support cuda12, and build from source it has tons of millions source to build even more than pytorch itself.....

I given it up due to my cuda is 12.1 don't want build a new enviroment for this...

**Comment by tslyellow** [comment]
I'm running it on a linux system, and I'm getting a little error following the steps you posted (the penultimate line of code isn't executing because of network issues, but executing the last line of code should have the same effect, right?) . Here's a picture of the problem I'm having, have you encountered this? If so, can you tell me how to fix it Thanks for the help!
![image](https://github.com/multimodal-art-projection/MAP-NEO/assets/97387908/e7e402bf-842e-421c-b07a-8510ce76adf3)

**Comment by tslyellow** [comment]
> I have run through it by following commands on Windows Anaconda platform. `conda create -n neo python=3.10` `pip install -r requirements.txt` `python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html` `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
> 
> Unfortunately I have to tell you is that the effect of pdf-parser is very mediocre, worse than calling the PPStructure when testing the Chinese paper pdf.

 哥们 运行完你的四个命令能直接运行代码嘛？ 我的还是不行欸，他老说cnstd库的xyxy24p不能导入，我看了一下源码，确实没有 你是怎么解决的呀？
 
![1719384151892](https://github.com/multimodal-art-projection/MAP-NEO/assets/97387908/98c7a5ec-4030-4387-989a-8e7e90a3603b)

**Comment by InsaneGe** [comment]
> > I have run through it by following commands on Windows Anaconda platform. `conda create -n neo python=3.10` `pip install -r requirements.txt` `python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html` `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
> > Unfortunately I have to tell you is that the effect of pdf-parser is very mediocre, worse than calling the PPStructure when testing the Chinese paper pdf.
> 
> 哥们 运行完你的四个命令能直接运行代码嘛？ 我的还是不行欸，他老说cnstd库的xyxy24p不能导入，我看了一下源码，确实没有 你是怎么解决的呀？
> 
> ![1719384151892](https://private-user-images.githubusercontent.com/97387908/343037146-98c7a5ec-4030-4387-989a-8e7e90a3603b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODQ2ODUsIm5iZiI6MTcxOTM4NDM4NSwicGF0aCI6Ii85NzM4NzkwOC8zNDMwMzcxNDYtOThjN2E1ZWMtNDAzMC00Mzg3LTk4OWEtOGU3ZTkwYTM2MDNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA2NDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYzVjOWI2ZDYwNGI5YjAwZDgzMjAyM2NjZjE2OWY1MTUxMTllOTAwMzExOGMxNmUyMDU2ZmRlM2FiNWUwMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qtrDE0XLQyW9SEyXXeKJuRlvk69rKRi01JbQZMarj40)

It may have something to do with the system platform, I remember I tried it on Ubuntu first, then on Windows it worked as shown above.

**Comment by tslyellow** [comment]
Thanks for the reply! I just started doing it on Linux like you and now it doesn't work on Windows either, too bad!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "multimodal-art-projection/MAP-NEO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [multimodal-art-projection/MAP-NEO] Can docment convert a standalone project? (Issue #4)





   
I have run through it by following commands on Windows Anaconda platform. conda create -n neo python=3.10 pip install -r requirements.txt python -m pip install fastdeploy-gpu-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
 Unfortunately I have to tell you is that the effect of pdf-parser is very mediocre, worse than calling the PPStructure when testing the Chinese paper pdf.
  
哥们 运行完你的四个命令能直接运行代码嘛？ 我的还是不行欸，他老说cnstd库的xyxy24p不能导入，我看了一下源码，确实没有 你是怎么解决的呀？
 

  
It may have something to do with the system platform, I remember I tried it on Ubuntu first, then on Windows it worked as shown above.

**Comment by wufenglailai** [comment]
@tslyellow 
老哥你是咋解决的啊，我在ubuntu上运行，也提示cnstd库的xyxy24p不能导入，是不是cnstd库装错了啊

```
Traceback (most recent call last):
  File "/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/site-packages/albumentations/check_version.py", line 29, in fetch_version_info
    with opener.open(url, timeout=2) as response:
  File "/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/mnt/nvme1n1/liuhengyu/workspace/python/MAP-NEO-main/Matrix/document-convert/multi_thread_process_to_doc.py", line 12, in <module>
    from latex.latex_rec import Latex2Text, sort_boxes
  File "/mnt/nvme1n1/liuhengyu/workspace/python/MAP-NEO-main/Matrix/document-convert/latex/latex_rec.py", line 24, in <module>
    from cnstd.yolov7.general import xyxy24p, box_partial_overlap
ImportError: cannot import name 'xyxy24p' from 'cnstd.yolov7.general' (/mnt/nvme1n1/liuhengyu/miniconda3/envs/map_lhy/lib/python3.10/site-packages/cnstd/yolov7/general.py)
```

**Comment by wufenglailai** [comment]
cnstd==1.2.3
似乎解决了  cannot import name 'xyxy24p' from 'cnstd.yolov7.general' 的报错。
