### ISSUE TITLE
UnboundLocalError: local variable 'imgs' referenced before assignment

### ISSUE THREAD

**Issue by 19157681683** [multimodal-art-projection/MAP-NEO#5]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/pdf_md/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/pdf_md/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/x32001214/data_handle/MAP-NEO-main/Matrix/document-convert/multi_thread_process_to_doc.py", line 169, in process_predict
    images = read_image(pdf_info[0])
  File "/x32001214/data_handle/MAP-NEO-main/Matrix/document-convert/utils.py", line 1418, in read_image
    return imgs
UnboundLocalError: local variable 'imgs' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/x32001214/data_handle/MAP-NEO-main/Matrix/document-convert/multi_thread_process_to_doc.py", line 348, in <module>
    pool.map(process_predict, file_info)
  File "/root/anaconda3/envs/pdf_md/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/anaconda3/envs/pdf_md/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
UnboundLocalError: local variable 'imgs' referenced before assignment

**Comment by Miki-lin** [comment]
![image](https://github.com/multimodal-art-projection/MAP-NEO/assets/54935281/d4504218-7191-4c43-82dd-14e5f344ace7)
I meet the same problem in running the multi_thread_process_to_doc.py, please tell me how to deal with this， thanks！

**Comment by 19157681683** [comment]
这个直接把Imgs放到循环前面

**Comment by 19157681683** [comment]
可以把问题，代码片段一起提交给DeepSeek/ChatGPT，然后跟着排错/调试就ok了

**Comment by Miki-lin** [comment]
我找到问题了，PDF那个文件夹下面不能包括输出的路径，最好是只有检测的PDF
